#MONITORING TOOL
#cadvisor:
#• Based on google/cadvisor:latest.
#• Namespace: kube-system.
#• Scheduled on all nodes.
#• Always restarts.
#• Exposes port 8080.
#

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor-daemonset
  namespace: kube-system

spec:
  selector:
    matchLabels:
      service: cadvisor
        #.spec.template.metadata.labels' is missing
  template:
    metadata:
      name: cadvisor
      labels:
        service: cadvisor-daemonset
        stage: gone  
    spec:
      restartPolicy: Always
      containers:
      - name: cadvisor-container
        image: google/cadvisor:latest
      
        ports:
          - containerPort: 8080
            #.spec.template.spec.volumes | lengtha
    #'volumes: ???   
