#MONITORING TOOL
#cadvisor:
#• Based on google/cadvisor:latest.
#• Namespace: kube-system.
#• Scheduled on all nodes.
#• Always restarts.
#• Exposes port 8080.
#

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cadvisor-daemonset
  namespace: kube-system
  annotations:
    kubernetes.io/pod: 'docker/default'

spec:
  selector:
    matchLabels:
      service: cadvisor-daemonset
      stage: gone  
        #.spec.template.metadata.labels' is missing
  template:
    metadata:
      name: cadvisor
      labels:
        service: cadvisor-daemonset
        stage: gone  
    spec:
      serviceAccountName: cadvisor
      restartPolicy: Always
      containers:
      - name: cadvisor-container
        image: google/cadvisor:latest
      
        ports:
          - containerPort: 8080
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
          readOnly: true
        - name: var-run
          mountPath: /var/run
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: true
        - name: docker
          mountPath: /var/lib/docker
          readOnly: true
        - name: disk
          mountPath: /dev/disk
          readOnly: true
            #.spec.template.spec.volumes | lengtha
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rootfs
        hostPath:
          path: /
      - name: var-run
        hostPath:
          path: /var/run
      - name: sys
        hostPath:
          path: /sys
      - name: docker
        hostPath:
          path: /var/lib/docker
      - name: disk
        hostPath:
          path: /dev/disk
