apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: default
  labels:
    type: local
    app: postgres-db
    stage: development  
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pers-volume-claim
  labels:
    app: postgres-db

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

