#• Environment variables:
#• POSTGRES_HOST
#• POSTGRES_PORT
#• POSTGRES_DB
#• POSTGRES_USER   -> ->
#• POSTGRES_PASSWORD -> -> 
#-> #POSTGRES_USER and POSTGRES_PASSWORD must be stored in Kubernetes’ Secrets.


apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: default
    #labels:
    #*****
data:
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: '5432'
    ##POSTGRES_DB: ???  
    ##postgres-host: postgres-service
    ##postgres-port: 5432
  ##postgres-db: ??? what should that be?? 
