apiVersion: v1
kind: Service     ## ClusterIP, default type
                  ## service is not available for external access (outside the clus#ter)
metadata:
  name: redis-service
  namespace: default  
spec:
  selector:
    app: redis
    stage: backstage
  type: ClusterIP  ## it is like this by default
  ports:
    - protocol: TCP
      port: 6379 
      targetPort: 6379

